# Generated by Django 6.0 on 2025-12-30 02:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Layanan')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Dasar')),
                ('estimated_duration', models.IntegerField(help_text='Durasi estimasi dalam menit', verbose_name='Estimasi Durasi (menit)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jenis Layanan',
                'verbose_name_plural': 'Jenis Layanan',
                'db_table': 'service_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='Plat Nomor')),
                ('brand', models.CharField(max_length=50, verbose_name='Merk')),
                ('model', models.CharField(max_length=50, verbose_name='Model/Tipe')),
                ('year', models.IntegerField(verbose_name='Tahun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motor',
                'db_table': 'motors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor Booking')),
                ('booking_type', models.CharField(choices=[('booking', 'Booking Online'), ('walk_in', 'Walk-in')], default='booking', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('assigned', 'Ditugaskan ke Mekanik'), ('in_progress', 'Sedang Dikerjakan'), ('finished', 'Selesai Dikerjakan'), ('paid', 'Sudah Dibayar'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('complaint', models.TextField(verbose_name='Keluhan/Permintaan')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan Tambahan')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Booking')),
                ('assigned_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Ditugaskan')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Mulai')),
                ('finish_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Selesai')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Pembayaran')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, limit_choices_to={'role': 'mechanic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_services', to=settings.AUTH_USER_MODEL)),
                ('motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='customer.motor')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customer.servicetype')),
            ],
            options={
                'verbose_name': 'Booking Servis',
                'verbose_name_plural': 'Booking Servis',
                'db_table': 'service_bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Nomor Invoice')),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Biaya Servis')),
                ('spare_parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biaya Suku Cadang')),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Biaya Tambahan')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Biaya')),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('debit', 'Kartu Debit'), ('credit', 'Kartu Kredit'), ('transfer', 'Transfer Bank'), ('ewallet', 'E-Wallet')], max_length=20, verbose_name='Metode Pembayaran')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jumlah Dibayar')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kembalian')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cashier', models.ForeignKey(limit_choices_to={'role': 'cashier'}, on_delete=django.db.models.deletion.PROTECT, related_name='processed_invoices', to=settings.AUTH_USER_MODEL)),
                ('service_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='customer.servicebooking')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoice',
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Jasa')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='customer.servicebooking')),
            ],
            options={
                'verbose_name': 'Jasa Tambahan',
                'verbose_name_plural': 'Jasa Tambahan',
                'db_table': 'additional_services',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Suku Cadang')),
                ('quantity', models.IntegerField(default=1, verbose_name='Jumlah')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Satuan')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Harga')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='customer.servicebooking')),
            ],
            options={
                'verbose_name': 'Suku Cadang',
                'verbose_name_plural': 'Suku Cadang',
                'db_table': 'spare_parts',
            },
        ),
    ]
