# Generated by Django 6.0 on 2025-12-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Catatan'),
        ),
    ]
