# Generated by Django 6.0 on 2025-12-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_restore_motor_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='notes',
        ),
    ]
