# Generated by Django 4.2.27 on 2026-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_motor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='specialization_category',
            field=models.CharField(choices=[('umum', 'Umum'), ('mesin', 'Mesin'), ('elektrikal', 'Elektrikal'), ('ban', 'Ban'), ('transmisi', 'Transmisi'), ('suspensi', 'Suspensi'), ('rem', 'Rem'), ('karburator', 'Karburator/Injeksi'), ('rantai_sproket', 'Rantai dan Sproket'), ('kopling', 'Kopling')], default='umum', max_length=50, verbose_name='Kategori Spesialisasi'),
        ),
    ]
