# Generated by Django 4.2.27 on 2026-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('umum', 'Umum'), ('mesin', 'Mesin'), ('elektrikal', 'Elektrikal'), ('ban', 'Ban'), ('transmisi', 'Transmisi'), ('suspensi', 'Suspensi'), ('body_work', 'Body Work'), ('ac', 'AC'), ('cat', 'Cat'), ('detailing', 'Detailing')], default='umum', max_length=50, null=True, verbose_name='Spesialisasi'),
        ),
    ]
